### ISSUE TITLE
Airplay 2 (HomeKit)

### ISSUE THREAD

**Issue by rcoe** [AetherThings/AetherCone#11]
What are the chances we can get an update for multiroom? Obviously, this project isn't a hardware partner of Apple, but I would certainly pay money (or write code) for an integration into HomeKit for my Cones.

https://techcrunch.com/2017/06/05/apples-airplay-2-brings-multi-room-audio-streaming-to-homekit-and-beyond/

**Comment by thhsam** [comment]
Who actually owns the codes, licenses etc, things needed for someone to write firmwares for the Cone?  The Cone is a beautiful piece of hardware and it is capable of doing more. It is a shame that the software development stops here.  Can someone buy all the things previously owned by AetherThings?

**Comment by martinwardley** [comment]
Is there any chance that the Airplay components will receive an automatic update from Apple to Airplay 2?

**Comment by rccoe** [comment]
From the press, it sounds like additional development will need to be done to upgrade the firmware to v2.

@aronrosenberg is there absolutely nothing we can do to get an upgrade? Can we get a firmware version with everything Apple & spotify stripped out so we can play around?

**Comment by rcoe** [comment]
From the press, it sounds like additional development will need to be done to upgrade the firmware to v2.

@aronrosenberg is there absolutely nothing we can do to get an upgrade? Can we get a firmware version with everything Apple & spotify stripped out so we can play around?

**Comment by aronrosenberg** [comment]
The Aether investors own all the software and control if the code can be released/open-sourced. I will ask them again if they are willing to open-source the final firmware. If it is open-sourced, assume that AirPlay and Spotify support would not be there.

**Comment by daleanthony** [comment]
@aronrosenberg any news? :)

**Comment by StevenStip** [comment]
@aronrosenberg It would be great if there could be an open source fork even if it would miss out on AirPlay and Spotify support.

**Comment by chrisbrown-io** [comment]
👍  +1 for open sourcing. I would love the ability to develop the existing firmware further, the hardware is capable of so much more!

**Comment by Muneesh22** [comment]
This would certainly be amazing to get a firmware version made available that supports Airplay2 for the AetherCone!
I'v bought a few cones round the house and would love to multi play from my IOS devices! (FYI you can do multiroom using iTunes with Airplay 1 devices - although the sync can be very slightly out)

looking forward to hearing if anyone can make this happen!!

**Comment by aronrosenberg** [comment]
I am still having a discussion with the investors about open sourcing the firmware. It may take a while.

**Comment by rccoe** [comment]
Thank you, @aronrosenberg 

Without knowing the specifics around the IP and financials, I can only speculate here, but I believe that open sourcing the Cone would be a smart financial move. Once Airplay 2 is out, these speakers will be outdated and undesirable for any new buyer, rendering the remaining inventory much less valuable. I bet there's a ton of demand out there for a hackable, open source, beautiful speaker. If you put the Cone with Airplay 2 alongside any of these newer, $400+ speakers with Airplay 2, it would be a much different story than with the current firmware.

**Comment by strickdogg** [comment]
@aronrosenberg and others... I'm wondering if any of you have had the issue I am having:

I finally set about updating the firmware, and the Aether Cone does not appear as a wifi network, rather it appears as an "Airplay Speaker" under my wifi networks. As such, I'm not able to connect to it directly via the IP address given.

When I select it, I'm taken to Airport Utility and it tries to connect the speaker to my wifi...

<img width="374" alt="screen shot 2017-10-20 at 1 12 48 pm" src="https://user-images.githubusercontent.com/32967991/31840100-a85e2358-b598-11e7-9299-10ebfed5b0ee.png">

<img width="695" alt="screen shot 2017-10-20 at 1 13 21 pm" src="https://user-images.githubusercontent.com/32967991/31840124-ba3d8f1e-b598-11e7-89b1-5d8fce0d65eb.png">


Any thoughts?

**Comment by aronrosenberg** [comment]
Just complete the process via AirPort Utility, then you can connect directly the IP address on your LAN to do the firmware update. If you can't find the IP address after setup, grab bonjour browser and look for the _aether._tcp record.

**Comment by rccoe** [comment]
@aronrosenberg I don't think you meant to close this issue, since it's about Airplay 2 and open source.

**Comment by edwardbattistini** [comment]
Airplay 2 !

**Comment by edwardbattistini** [comment]
There is such big potential for a decent airplay speaker

**Comment by edwardbattistini** [comment]
I would actually pay for an update

**Comment by mhvp** [comment]
I would also pay for an update as i have 10 of them...

**Comment by edwardbattistini** [comment]
@mhvp could describe your setup ? Please ? I have one but I really love them and want to have more. How do you use them ?

**Comment by mhvp** [comment]
They are all set up on the Wi-Fi network,  then I use airfoil https://rogueamoeba.com/airfoil/
 it works pretty good you need to adjust some of the speakers for timing issues in the software.

**Comment by edwardbattistini** [comment]
Thanks for the tips ! It does sound like you always have a computer running airfoil then

**Comment by mhvp** [comment]
Yes I have a computer in a comms cabinet that runs continuously. It does many things including running Plex and airfoil along with a home assistance server.

**Comment by edwardbattistini** [comment]
I have a NAS and I’m wondering if airfoil could run on a Linux OS will check that

**Comment by edwardbattistini** [comment]
Does the cone can handle airplay 2 ?
