### ISSUE TITLE
Cone sending out thousands of DNS requests

### ISSUE THREAD

**Issue by stephenpperry** [AetherThings/AetherCone#2]
I took a look at my routers Dns info and found that the Cone is sharing out thousands of requests to connectivity.aether.net and api.aether.net 

I don't believe it's expected behavior (potentially a risk if the domain gets sold)

**Comment by aronrosenberg** [comment]
Did you upgrade to the final firmware? The connectivity check should be gone from that one. The api.aether.net one is the Cone checking if new firmware is available. That should only be done once every two weeks in the final firmware. That domain is still under my control and won't be purchased by anybody else. In addition, without the code signing keys, even control of the aether.net domain wouldn't allow firmware to be changed.

**Comment by stephenpperry** [comment]
Hello Aron, thanks for the reply, I'm on the final firmware, I checked and rechecked, but having had a look at my DNS requests I can see that even now the cone is still sending out thousands of requests each day. So far today its done 8579 requests to connectivity.aether.net and 1172 to api.aether.net. While I appreciate you own the domains it seems unnecessary that it should be pinging constantly when theres no update server in place.

**Comment by stephenpperry** [comment]
@aronrosenberg see above (apologies I cant re-open the bug)

**Comment by aronrosenberg** [comment]
You are not on the final firmware if you are seeing DNS requests for connectivity.aether.net. What does the version number show on the firmware page?

**Comment by stephenpperry** [comment]
The version is: FRM000104.03.01.0013 I checked and took a screenshot, the server requests still persist. 
![screen shot 2017-03-06 at 16 05 45](https://cloud.githubusercontent.com/assets/4229042/23618095/23924092-0287-11e7-957c-1c9a2f0b254c.png)

**Comment by stephenpperry** [comment]
and here's a sc reenshot from my piHole (where I've blocked the domains) 
![screen shot 2017-03-06 at 16 11 15](https://cloud.githubusercontent.com/assets/4229042/23618220/9490e9ce-0287-11e7-80eb-b4f77eb28ebf.png)

**Comment by aronrosenberg** [comment]
Do you have more than one Cone? Could another one not be in the final firmware? Either way, there isn't anything we can do about it, since I have no longer have the ability to create firmware images

**Comment by stephenpperry** [comment]
Nope just the one cone. 

Is there no way anyone can sign firmware for these going forwards? I.e open source it all? Or will this be it in terms of updates ?

**Comment by stephenpperry** [comment]
Also forgot to say thankyou for helping out and replying Aron! 👍

**Comment by aronrosenberg** [comment]
All code that was required and allowed; was open-sourced. See the legal-info.tgz file. There won't be any more firmware updates, as the infrastructure to do that disappeared when the company shut-down.
