### ISSUE TITLE
Old firmware restored after Factory Reset

### ISSUE THREAD

**Issue by rcarlsen** [AetherThings/AetherCone#4]
While troubleshooting Bluetooth pairing on the final firmware build, I performed the Factory Reset described in the wiki of this repo.

After rebooting, the cone no longer seemed to support Bluetooth pairing mode (ie. hold Volume + and tapping the center button thrice would only show the amber ring rather than the blue pairing pulse).

I was able to connect to the cone over Wifi in setup mode, but the root of the web server only shows "Configure this Cone" as an unstyled HTML text link. There doesn't seem to be a button labeled "About this Cone" and I'm unable to follow the wiki instructions to manually update the firmware.

Using a mDNS browser, I can see the cone advertising _aether._tcp. In the details of that service the version key has a value of 2014.18dev (build-tag:FRM000104.01.02.0007; rev:d4371f0)

How can I update the firmware of this cone to the final version?
Thanks.

**Comment by aronrosenberg** [comment]
Sorry to have not seen this earlier. If you still have issues, send me an email at aron@aether.com and I will work with you to bootstrap back to the final firmware. You reverted to the original original factory firmware which only had support for Apple WAC.
