### ISSUE TITLE
Aux in possible?

### ISSUE THREAD

**Issue by tim290480** [AetherThings/AetherCone#5]
While this is a fantastic piece of kit and I'm very happy with the connectivity and sound quality, I was wondering if there was some way of adding an aux in to make it compatible with a Chromecast audio. I know that this wasn't the intended purpose for the device but it really would be the icing on the cake.

**Comment by nano2yk** [comment]
I second this, I have the Amazon Echo and Firestick and neither will pair.  Even bought a AUX to Bluetooth transmitter but it would not pair.   But maybe another model would?

**Comment by nano2yk** [comment]
I live in Thailand so it was probably a cheap Chinese piece of crap.  But a more robust BT TX may work for you?

**Comment by aronrosenberg** [comment]
No, the hardware didn't have any support for Aux In.
