### ISSUE TITLE
Bluebooth issues

### ISSUE THREAD

**Issue by pk-nova** [AetherThings/AetherCone#6]
I purchased an Aether Cone on sale & it has the latest firmware - since the off i have had issues pairing devices via bluetooth, i get the message 'unable to communicate with aether cone' - i have tried multiple devices (android phones and IOS) and both have the same issues. Spotify connect however works perfectly! 

I did manage to get the device paired once however next time i tried to pair it failed with the same message.

Any ideas?

**Comment by thhsam** [comment]
I am having the same problem too...

**Comment by stephenpperry** [comment]
Pairing has also been a problem for me with some devices. for example amazon echo will just not pair with it.

**Comment by nutwiss** [comment]
I have the same issue. I can pair one device, then I have to hard reset the cone to pair any other devices. It's a rea shame it can't act like any other Bluetooth receiver.

**Comment by aronrosenberg** [comment]
We were never able to work out the last of the Bluetooth Pairing issues on the final firmware.

**Comment by robotiko** [comment]
Another one with the same issues.
pairing problem and connection lost after a few mins. 
Quite unusable.

**Comment by madmat01** [comment]
Same here, I've updated to this latest firmware and cannot get the Aether Cone to pair to any device at all.
