### ISSUE TITLE
Custom firmware?

### ISSUE THREAD

**Issue by sconisbee** [AetherThings/AetherCone#7]
Hi team, has anyone developed a custom ROM for this device or is that a possibility? Would be great to see the voice control back.

**Comment by awilkins** [comment]
AFAICT from comments here :

* The device is locked down, the firmware upload routine only accepts signed images
* Without the signing keys you can't make your own firmware

The hardware is therefore [Tivoized](https://en.m.wikipedia.org/wiki/Tivoization).

**Comment by awilkins** [comment]
Apologies for the second comment, hit the send button on my phone by accident.

The device itself seems to be running Linux of some sort. OpenSSH 6.6 is available on port 22.

The developer who has kindly uploaded the last official firmware and the legally required licensed source code presumably at least had access to the signing keys at one point, and may also know if there are any users accounts the SSH server will respond to, what their passwords are, and if any of them have root, and whether the firmware signature check is confined to the update mechanism or is also part of the bootloader.

Sadly the state of IP laws means that this information is considered copyright property of the original manufacturer. There may also be further proprietary code that the Aether Cone requires to operate (e.g user space device drivers, the management web service) that are not available to be released.

Best case AFAICT :

* The device is composed of mostly commodity hardware that has current in-kernel drivers
* A method to sign a firmware image or bypass the firmware signature check is found, and the

Worst case

**Comment by aronrosenberg** [comment]
The signature check was just on the update and web upload mechanism. I am unable to release the signing-keys at this time.
