### ISSUE TITLE
Request - fully open source the Aether Cone project. 

### ISSUE THREAD

**Issue by stephenpperry** [AetherThings/AetherCone#8]
Given that Aether is sadly gone for this to be a sustainable product going forwards it would be really cool to see it opened up to others to develop, fork, sign and install on their cones. And also share out for others. The product is beautiful and has so much potential. For example an equalizer UI to change audio settings and levels would be cool, updates to the airplay version included, amazon alexa integration using the mic, bringing back voice controls, an IFTTT skill. 

All these things could make the cone even cooler, and opening it up to let others work on the codebase could benefit everyone. 

Just a thought (or a few thoughts) :)

**Comment by robotiko** [comment]
+1

**Comment by StevenStip** [comment]
+1

**Comment by aronrosenberg** [comment]
I wish we could have, but it wasn't allowed by Apple or Spotify rules.

**Comment by StevenStip** [comment]
Is there a way to get a little more access to the device instead, such as maybe ssh credentials?
